---
- name: Install nginx
  package:
    name:
      - nginx
      - php
      - php-cli
      - mysql-server
      - python3-pymysql
      - php-fpm
      - php-mysql
      - php-curl
      - php-common
    state: latest
    update_cache: true