---
- name: Ensure a locale exists
  locale_gen:
    name: de_CH.UTF-8
    state: present

- name: Set timezone to Europe/Zurich
  timezone:
    name: Europe/Zurich

- name: Wait for automatic system updates to complete
  shell: while pgrep unattended; do sleep 10; done;

- name: Update Package Cache (apt/Ubuntu)
  tags: always
  apt:
    update_cache: yes
    upgrade: full
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: Install qemu-guest-agent, ntp
  package:
    name:
      - qemu-guest-agent
      - ntp
      - python3
      - ufw
      - fail2ban
      - policycoreutils 
      - libpam-pwquality
    state: latest

- name: Recursively change ownership of a directory
  file:
    path: /etc/update-motd.d/
    state: directory
    recurse: yes
    mode: -x

- name: Copy motd to remote
  copy:
    src: motd
    dest: /etc/motd
    mode: '0644'

- name: Copy SSH config to remote
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    mode: '0644'

- name: Copy pam config to remote
  copy:
    src: common-password
    dest: /etc/pam.d/common-password
    mode: '0644'

- name: Copy jail2ban config to remote
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    mode: '0644'

- name: Copy pwquality config to remote
  copy:
    src: pwquality.conf 
    dest: /etc/security/pwquality.conf 
    mode: '0644'

- name: Copy legal to legal.bak
  copy: 
    remote_src: True 
    src: /etc/legal
    dest: /etc/legal.bak 
  ignore_errors: true
  
- name: Remove legal
  file: 
    path: /etc/legal
    state: absent
  ignore_errors: true

- name: Enable IPv4 Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Ensure keyboard layout to be de-CH
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBLAYOUT='
    line: XKBLAYOUT="de-CH"

- name: Ensure keyboard variant tobe nodeadkeys
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBVARIANT='
    line: XKBVARIANT="nodeadkeys"

- name: Start service qemu-guest-agent, if not started
  service:
    name: qemu-guest-agent
    state: started
    enabled: true