---
- name: Create and start services
  docker_compose:
    project_name: sdx
    definition:
      version: "3"
      services:
        proxy: 
          image: isaacwuerth/sdx-proxy:main
          restart: always
          ports:
            - 80:80
          depends_on:
            - web
            - api

        web:
          image: isaacwuerth/sdx-web:main
          restart: always
          environment:
            - API_URL=https://sdx.itsvc.ch
        
        api:
          image: isaacwuerth/sdx-api:main
          restart: always
          environment:
            - ASPNETCORE_ENVIRONMENT=Production