---
- name: Configure Terraform Agent
  hosts: all

  tasks:
    - name: Disable Host Key Checking 
      community.general.ssh_config:
        host: "*"
        strict_host_key_checking: "no"